### ISSUE TITLE
error in multi_decoder

### ISSUE THREAD

**Issue by johndpope** [srikarmv/Style-transfer-in-text-using-Adverserial-Learning#1]
according to paper - this is supposedly the best model.

training works.
python train_nmt.py
{'model': ['../models/model.npz'], 'dim_word': [64], 'dim': [32], 'n-words': [100000], 'optimizer': ['adadelta'], 'decay-c': [0.0], 'use-dropout': [False], 'learning-rate': [0.0001], 'reload': [False]}
Loading data
Building model
Building sampler
Building f_init... Done

I added the model.npz from another github repo

THEANO_FLAGS='floatX=float32'  python ./translate.py -n -p 10 \
	models/model.npz  \
	../data/dict.pkl \
	../data/dict.pkl \
	../data/q_test.txt \
	./q_test_style0.txt

  File "/Users/admin/miniconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/admin/miniconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./translate.py", line 19, in translate_model
    params = init_params(options)
  File "/Users/admin/Documents/mlWorkspace/Style-transfer-in-text-using-Adverserial-Learning/multi_decoder/nmt.py", line 411, in init_params
    params = get_layer(options['encoder'])[0](options, params,
  File "/Users/admin/Documents/mlWorkspace/Style-transfer-in-text-using-Adverserial-Learning/multi_decoder/nmt.py", line 78, in get_layer
    fns = layers[name]
KeyError: 'lstm'
Process Process-7:
Traceback (most recent call last):
  File "/Users/admin/miniconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/admin/miniconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./translate.py", line 19, in translate_model
    params = init_params(options)
  File "/Users/admin/Documents/mlWorkspace/Style-transfer-in-text-using-Adverserial-Learning/multi_decoder/nmt.py", line 411, in init_params
    params = get_layer(options['encoder'])[0](options, params,
  File "/Users/admin/Documents/mlWorkspace/Style-transfer-in-text-using-Adverserial-Learning/multi_decoder/nmt.py", line 78, in get_layer
    fns = layers[name]
KeyError: 'lstm'

**Comment by johndpope** [comment]
yielding to this other repo - https://github.com/johndpope/text-style-transfer-gan
